remote_theme: "mmistakes/minimal-mistakes@4.27.1"

title: "Prof. Domenico Amalfitano"
name: "Prof. Domenico Amalfitano"
description: "Associate Professor in Computer Engineering (IINF-05/A)"

plugins:
  - jekyll-include-cache

author:
  name: "Prof. Domenico Amalfitano"
  bio: "Associate Professor at DIETI, University of Naples Federico II"
  location: "Naples, Italy"

  email: "domenico[dot]amalfitano[at]unina[dot]it"

  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=ReafO6YAAAAJ"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0002-4761-4443"
